from .algoritmo_base               import AlgoritmoBase
from .naiv_on_array                import NaivOnArray
from .naiv_loop_unrolling_two      import NaivLoopUnrollingTwo
from .naiv_loop_unrolling_four     import NaivLoopUnrollingFour
from .winograd_original            import WinogradOriginal
from .winograd_scaled              import WinogradScaled
from .strassen_naiv                import StrassenNaiv
from .strassen_winograd            import StrassenWinograd
from .sequential_block_III3        import SequentialBlockIII3
from .parallel_block_III4          import ParallelBlockIII4
from .enhanced_parallel_block_III5 import EnhancedParallelBlockIII5
from .sequential_block_IV3         import SequentialBlockIV3
from .parallel_block_IV4           import ParallelBlockIV4
from .enhanced_parallel_block_IV5  import EnhancedParallelBlockIV5
from .sequential_block_V3          import SequentialBlockV3
from .parallel_block_V4            import ParallelBlockV4